# Generated by Django 4.2.2 on 2023-06-21 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advert_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='dateTimeCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
